name: Promote Release Candidate Version

on:
  workflow_dispatch:
    inputs:
      release_candidate_version:
        description: 'Release candidate'
        required: true
        type: string
      release_version:
        description: 'Release version'
        required: true
        type: string
      release_notes:
        description: 'Release notes text (use \n for new lines)'
        required: true
        type: string

jobs:
  promote-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "dhavalmehtatrilogy"
          git config --global user.email "dhaval.mehta@trilogy.com"
      - name: Create Git Tag
        run: |
          if [ $(git tag -l "${{ github.event.inputs.release_version }}") ]; then
            echo "Tag ${{ github.event.inputs.release_version }} already exists"
          else
            git tag ${{ github.event.inputs.release_version }} ${{ github.event.inputs.release_candidate_version }}
            git push origin ${{ github.event.inputs.release_version }}
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          name: ${{ github.event.inputs.release_version }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
